name: hrv-eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24
  - pandas>=2.0
  - matplotlib>=3.7
  - scikit-learn>=1.3
  - scipy>=1.10          # Mann–Whitney U 檢定（可選，但建議裝）
  - openpyxl>=3.1        # 讀 Excel
  - xlsxwriter>=3.1      # 寫 Excel（engine="xlsxwriter"）
  - jupyterlab>=4.0      # 或改裝 notebook 也可
  - ipykernel
  - nbformat